server:
  port: 8080
ws:
  pokemon:
    url: 'http://localhost:8081/retrieve-pokemon/'
  skill:
    url: 'http://localhost:8081/retrieve-skill/'
  coin:
    url: 'http://localhost:8082/retrieve-coin/'